mqtt:
  #?????
  rec-topic: mqtt/hq/+/Rec
  #??????
  keep-alive: 30
  #mqtt???????
  broker: tcp://172.16.102.133:1883
  #?????
  client-id: 135928115961596730441_slave1
  #?????
  username: duzhaosongyue
  password: jishuzhai
